### ISSUE TITLE
Bring up to speed with SwiftDux 2.0

### ISSUE THREAD

**Issue by hoopes** [StevenLambion/SwiftDuxNavigation#18]
This lib relies on SwiftDux < 2 (accd to SPM, anyway...). Can you make a release compatible with SwiftDux 2.0 please?

Thanks!

**Comment by hoopes** [comment]
Neeeeeevvvvvvvverrrrrr mind. I obviously can't click the right buttons in xcode. Apologies.

**Comment by StevenLambion** [comment]
No worries, I just made a new beta tag for version 2.0.0. This is what's been on the master branch for the last couple weeks. The API has significant differences from the version 1.0.0 tag that improves overall performance and compatibility with SwiftUI in iOS 14.
